### ISSUE TITLE
token-sys applet goes blank after sending Manual Debit transaction

### ISSUE THREAD

**Issue by shakhruz** [gofractally/psibase#253]
Everything worked fine until I sent with manual debit option turned on. After that page reloaded into blank (see screenshot) and I found js errors in the console:

index.js:32 RangeError: Invalid time value
    at Ms (index.js:40:43475)
    at Bv (index.js:40:53102)
    at index.js:40:54761
    at Array.map (<anonymous>)
    at Qv (index.js:40:54500)
    at Au (index.js:30:19519)
    at jo (index.js:32:3169)
    at If (index.js:32:45025)
    at Rf (index.js:32:39937)
    at gm (index.js:32:39865)
Wo @ index.js:32
n.callback @ index.js:32
Ya @ index.js:30
ss @ index.js:32
Mf @ index.js:32
hm @ index.js:32
Sm @ index.js:32
nn @ index.js:32
Lf @ index.js:32
N @ index.js:17
j @ index.js:17
index.js:40 Uncaught RangeError: Invalid time value
    at Ms (index.js:40:43475)
    at Bv (index.js:40:53102)
    at index.js:40:54761
    at Array.map (<anonymous>)
    at Qv (index.js:40:54500)
    at Au (index.js:30:19519)
    at jo (index.js:32:3169)
    at If (index.js:32:45025)
    at Rf (index.js:32:39937)
    at gm (index.js:32:39865)
    
    
![2022-12-01_00-19-25](https://user-images.githubusercontent.com/6615/204889371-c3061686-19a4-4a39-87c7-e8331da66abf.png)

**Comment by James-Mart** [comment]
App has been reworked
